name: pr-auto-approve

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto approve if author is specific user
        if: github.event.pull_request.user.login == 'wen-yan'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
