name: pr

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  pr-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.106

      - name: Build solution - ${{ matrix.configuration }}
        run: dotnet build --configuration ${{ matrix.configuration }}
        working-directory: ./src
